# Generated by Django 5.2.1 on 2025-06-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('furigana', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('zip_code', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('building', models.CharField(max_length=200)),
                ('inquiry', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
